In [2]:
# Aggregation and GroupBy (Pandas) – Detailed Explanation

# Data Analysis me GroupBy + Aggregation bahut important concept hai. 
# Iska use hum data ko category wise group karke summary nikalne ke liye karte hain.

In [4]:
# 🔷 1. GroupBy kya hota hai?

# 👉 groupby() ka matlab:

# “Same category wale data ko group karo”

# Example:

# Department wise salary
# City wise sales
# Gender wise marks

# df.groupby('column_name')

In [3]:
import pandas as pd

In [5]:
data = {
    'Name': ['Ram', 'Ravi', 'Amit', 'Ram', 'Ravi'],
    'Dept': ['IT', 'HR', 'IT', 'HR', 'IT'],
    'Salary': [30000, 25000, 40000, 32000, 28000]
}

df = pd.DataFrame(data)

In [6]:
df

   Name Dept  Salary
0   Ram   IT   30000
1  Ravi   HR   25000
2  Amit   IT   40000
3   Ram   HR   32000
4  Ravi   IT   28000

In [8]:
# 2. Aggregation kya hota hai?
# "Grouped data par calculation karna"

# Common functions:
# sum()
# mean()
# min()
# max()
# count()

In [11]:
df['Dept'].value_counts()  # frequency of values in month column

Dept
IT    3
HR    2
Name: count, dtype: int64

In [12]:
df[df['Dept']=='IT'].value_counts()  # frequency of values in month column where month = 1

Name  Dept  Salary
Ram   IT    30000     1
Amit  IT    40000     1
Ravi  IT    28000     1
Name: count, dtype: int64

In [14]:
# Department  wise total salary  ['Salary'] Aggregation
df.groupby('Dept')['Salary'].sum()

Dept
HR    57000
IT    98000
Name: Salary, dtype: int64

In [16]:
#Department wise Average Salary 
df.groupby('Dept')['Salary'].count()

Dept
HR    2
IT    3
Name: Salary, dtype: int64

In [17]:
#count of employees per department 
df.groupby('Dept')['Name'].count()

Dept
HR    2
IT    3
Name: Name, dtype: int64

In [18]:
#Multiple aggregartions (Most Important)
df.groupby('Dept')['Salary'].agg(['sum','mean','min','max'])

        sum          mean    min    max
Dept
HR    57000  28500.000000  25000  32000
IT    98000  32666.666667  28000  40000

In [19]:
#Multiple column group by Dept + Name combination wise result 
df.groupby(['Dept','Name'])['Salary'].sum()

Dept  Name
HR    Ram     32000
      Ravi    25000
IT    Amit    40000
      Ram     30000
      Ravi    28000
Name: Salary, dtype: int64

In [20]:
#Named Aggregation (Advanced)
df.groupby('Dept').agg(
    total_salary = ('Salary','sum'),
    avg_salary = ('Salary','mean'),
    count_emp = ('Name','count')
)

      total_salary    avg_salary  count_emp
Dept
HR           57000  28500.000000          2
IT           98000  32666.666667          3