In [1]:
#Basic DataFrame Understanding

In [1]:
import pandas as pd

C:\Users\bkrat\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
data = {
    'Name': ['ram', 'ravi', 'ak', 'vj',"av","rj"],
    'Age': [26,37,28,19,4,3],
    'Salary': [10000, 3000, 40000, 50000,555,777]

}

In [3]:
df = pd.DataFrame(data)
print(df)

   Name  Age  Salary
0   ram   26   10000
1  ravi   37    3000
2    ak   28   40000
3    vj   19   50000
4    av    4     555
5    rj    3     777

In [4]:
df.head() # by default 5 rows show karta hai

   Name  Age  Salary
0   ram   26   10000
1  ravi   37    3000
2    ak   28   40000
3    vj   19   50000
4    av    4     555

In [10]:
df.head(2) #top 2 rows show karta hai

   Name  Age  Salary
0   ram   26   10000
1  ravi   37    3000

In [14]:
df.tail() # by default  last  5 rows

   Name  Age  Salary
1  ravi   37    3000
2    ak   28   40000
3    vj   19   50000
4    av    4     555
5    rj    3     777

In [15]:
df.tail(2) #show 2 last rows

  Name  Age  Salary
4   av    4     555
5   rj    3     777

In [16]:
df.shape #returns a tuple containing the shape of the Dataframe - rows & columns

(6, 3)

In [17]:
df.columns #list of column names in a dataframe

Index(['Name', 'Age', 'Salary'], dtype='str')

In [18]:
df.rename(columns ={'Salary': 'Monthly_Salary1'}) # (temporary change ) rename abhi dataframe mai change nai hua hai

   Name  Age  Monthly_Salary1
0   ram   26            10000
1  ravi   37             3000
2    ak   28            40000
3    vj   19            50000
4    av    4              555
5    rj    3              777

In [19]:
df #abhi dataframe mai change nahi hua hai

   Name  Age  Salary
0   ram   26   10000
1  ravi   37    3000
2    ak   28   40000
3    vj   19   50000
4    av    4     555
5    rj    3     777

In [20]:
df.rename(columns ={'Salary': 'Monthly_Salary1'},inplace=True) # (permanent change ) rename columns name

In [21]:
df

   Name  Age  Monthly_Salary1
0   ram   26            10000
1  ravi   37             3000
2    ak   28            40000
3    vj   19            50000
4    av    4              555
5    rj    3              777

In [22]:
df.info() # info methods prints information about the dataframe

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             6 non-null      str
 1   Age              6 non-null      int64
 2   Monthly_Salary1  6 non-null      int64
dtypes: int64(2), str(1)
memory usage: 291.0 bytes

In [23]:
df.describe() # descirbe method generates descriptive  statistics of Dataframes ,
#only for numerical - value coulmns

             Age  Monthly_Salary1
count   6.000000         6.000000
mean   19.500000     17388.666667
std    13.663821     21889.346191
min     3.000000       555.000000
25%     7.750000      1332.750000
50%    22.500000      6500.000000
75%    27.500000     32500.000000
max    37.000000     50000.000000

In [24]:
#save and load data  from csv 
df.to_csv('pn_data.csv')

In [25]:
df.to_csv('pn_data.csv',index = False) # save file - export data frame