In [1]:
# 1. Concatenate (DataFrames ko jodna)

# 👉 concat() ka use hota hai:

# Multiple DataFrames ko stack (upar-neeche ya side-by-side) jodne ke liye
# pd.concat([df1, df2])

In [2]:
import pandas as pd

C:\Users\bkrat\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [4]:
df1 = pd.DataFrame({
    'Name':['Ram','Ravi'],
    'Age':[25,30]
})

df2 = pd.DataFrame({
    'Name':['Amit','Sita'],
    'Age':[28,22]
})
# result = pd.concat([df1, df2],axis=0) #Concatenate: vertical / row Level / top on top
result = pd.concat([df1, df2], axis=1) ## Concatenate: horizontal / column Level / side on side

result

   Name  Age  Name  Age
0   Ram   25  Amit   28
1  Ravi   30  Sita   22

In [8]:
# Merge in Pandas
# Performs join operations similar to relational databases like SQL JOINS

df1 = pd.DataFrame({
    'EmpID': [1, 2, 3],
    'Name': ['Ram', 'Ravi', 'Amit']
})
df2 = pd.DataFrame({
    'EmpID': [1, 2, 4],
    'Salary': [30000, 40000, 50000]

})

In [9]:
pd.merge(df1,df2,on = 'EmpID')  #inner Join (default ) sirf matching data

   EmpID  Name  Salary
0      1   Ram   30000
1      2  Ravi   40000

In [10]:
#LEft Join Left table ka sab data + matching right 
pd.merge(df1,df2,on= ['EmpID'],how = 'left')

   EmpID  Name   Salary
0      1   Ram  30000.0
1      2  Ravi  40000.0
2      3  Amit      NaN

In [12]:
#Right Join means right table ka sab data + matching data 
pd.merge(df1,df2,on = ['EmpID'],how = 'right')

   EmpID  Name  Salary
0      1   Ram   30000
1      2  Ravi   40000
2      4   NaN   50000

In [13]:
#Outer Join sab data dono tables ka 
pd.merge(df1,df2, on = ['EmpID'],how = 'outer')

   EmpID  Name   Salary
0      1   Ram  30000.0
1      2  Ravi  40000.0
2      3  Amit      NaN
3      4   NaN  50000.0

In [14]:
#Join type Result 
#inner only matching
#left left +matching right
#right  right + matching left 
#outer  All data

In [15]:
pd.merge(df1,df2, how = 'inner', left_on = 'EmpID',right_on='EmpID') # dono table mai name alag ho tab

   EmpID  Name  Salary
0      1   Ram   30000
1      2  Ravi   40000