In [4]:
import pandas as pd
import matplotlib.pyplot as plt

data = {
    "Name": ["Aman", "Riya", "Karan", "Neha", "Rahul",
             "Priya", "Arjun", "Simran", "Vikas", "Anjali"],

    "Branch": ["CSE", "CSE", "ECE", "ECE", "CSE",
               "IT", "IT", "CSE", "ECE", "IT"],

    "Gender": ["M", "F", "M", "F", "M",
               "F", "M", "F", "M", "F"],

    "Marks": [85, 92, 67, 74, 78, 88, 95, 81, 69, 90],

    "Attendance": [90, 95, 75, 80, 85, 92, 98, 88, 72, 94]
}

df = pd.DataFrame(data)

print(df)

     Name Branch Gender  Marks  Attendance
0    Aman    CSE      M     85          90
1    Riya    CSE      F     92          95
2   Karan    ECE      M     67          75
3    Neha    ECE      F     74          80
4   Rahul    CSE      M     78          85
5   Priya     IT      F     88          92
6   Arjun     IT      M     95          98
7  Simran    CSE      F     81          88
8   Vikas    ECE      M     69          72
9  Anjali     IT      F     90          94

In [5]:
# Display the first 5 rows.
df.head()

    Name Branch Gender  Marks  Attendance
0   Aman    CSE      M     85          90
1   Riya    CSE      F     92          95
2  Karan    ECE      M     67          75
3   Neha    ECE      F     74          80
4  Rahul    CSE      M     78          85

In [6]:
# Display the last 5 rows.
df.tail()

     Name Branch Gender  Marks  Attendance
5   Priya     IT      F     88          92
6   Arjun     IT      M     95          98
7  Simran    CSE      F     81          88
8   Vikas    ECE      M     69          72
9  Anjali     IT      F     90          94

In [7]:
# Display the shape of the DataFrame.
df.shape

(10, 5)

In [8]:
# Display the column names.
df.columns

Index(['Name', 'Branch', 'Gender', 'Marks', 'Attendance'], dtype='str')

In [10]:
# Display basic statistical information about the numerical columns.
df.describe()

           Marks  Attendance
count  10.000000   10.000000
mean   81.900000   86.900000
std     9.734817    8.761659
min    67.000000   72.000000
25%    75.000000   81.250000
50%    83.000000   89.000000
75%    89.500000   93.500000
max    95.000000   98.000000

In [11]:
# Check whether any missing values are present.
df.isnull()

    Name  Branch  Gender  Marks  Attendance
0  False   False   False  False       False
1  False   False   False  False       False
2  False   False   False  False       False
3  False   False   False  False       False
4  False   False   False  False       False
5  False   False   False  False       False
6  False   False   False  False       False
7  False   False   False  False       False
8  False   False   False  False       False
9  False   False   False  False       False

In [12]:
# Display only the Name/student-name column.
df['Name']

0      Aman
1      Riya
2     Karan
3      Neha
4     Rahul
5     Priya
6     Arjun
7    Simran
8     Vikas
9    Anjali
Name: Name, dtype: str

In [13]:
# Display Marks and Attendance.
df[['Marks','Attendance']]

   Marks  Attendance
0     85          90
1     92          95
2     67          75
3     74          80
4     78          85
5     88          92
6     95          98
7     81          88
8     69          72
9     90          94

In [14]:
df.loc[df['Name']=='Simran']

     Name Branch Gender  Marks  Attendance
7  Simran    CSE      F     81          88

In [25]:
df.loc[df[['Marks','Branch']]]

ValueError: Cannot index with multidimensional key