In [1]:

# 📊 Project 2: Sales Analysis Report (Pandas)
# 🎯 Goal:

# Ek shop / company ke sales data se:

# Product wise sales
# Region wise revenue
# Best selling product
# Total profit analysis

In [2]:
import pandas as pd

C:\Users\bkrat\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [3]:
data = {
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Laptop', 'Mouse', 'Keyboard', 'Laptop'],
    'Region': ['North', 'South', 'North', 'South', 'North', 'South', 'North'],
    'Sales': [50000, 500, 1500, 55000, 600, 1400, 60000],
    'Profit': [8000, 100, 300, 9000, 120, 280, 10000]
}

df = pd.DataFrame(data)
df

    Product Region  Sales  Profit
0    Laptop  North  50000    8000
1     Mouse  South    500     100
2  Keyboard  North   1500     300
3    Laptop  South  55000    9000
4     Mouse  North    600     120
5  Keyboard  South   1400     280
6    Laptop  North  60000   10000

In [5]:
#product wise total sale 
df.groupby('Product')['Sales'].sum()

Product
Keyboard      2900
Laptop      165000
Mouse         1100
Name: Sales, dtype: int64

In [6]:
#product wise average profit
df.groupby('Product')['Profit'].mean()

Product
Keyboard     290.0
Laptop      9000.0
Mouse        110.0
Name: Profit, dtype: float64

In [8]:
#Region wise total sale 
df.groupby('Region')['Sales'].sum()

Region
North    112100
South     56900
Name: Sales, dtype: int64

In [9]:
#Region wise profit 
df.groupby('Region')['Profit'].sum()

Region
North    18420
South     9380
Name: Profit, dtype: int64

In [10]:
#Best selling product 
df.groupby('Product')['Sales'].sum().sort_values(ascending=False)

Product
Laptop      165000
Keyboard      2900
Mouse         1100
Name: Sales, dtype: int64

In [11]:
#full business Report 
report = df.groupby('Product').agg(
    total_sales = ('Sales','sum'),
    avg_sales = ('Sales','mean'),
    total_profit=('Profit', 'sum'),
    avg_profit=('Profit', 'mean')
)
report

          total_sales  avg_sales  total_profit  avg_profit
Product
Keyboard         2900     1450.0           580       290.0
Laptop         165000    55000.0         27000      9000.0
Mouse            1100      550.0           220       110.0

In [12]:
#Top performing
df.groupby('Region')['Sales'].sum().sort_values(ascending=False)

Region
North    112100
South     56900
Name: Sales, dtype: int64

In [13]:
# GroupBy = category wise data split
#Aggregation = business insight nikalna