In [1]:
import pandas as pd

C:\Users\bkrat\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
df = pd.read_csv('pn_data.csv')  #Load file - import dataframe
df

   Name  Age  Monthly_Salary1
0   ram   26            10000
1  ravi   37             3000
2    ak   28            40000
3    vj   19            50000
4    av    4              555
5    rj    3              777

In [3]:
#rows and columns -Selection

In [4]:
df['Name']

0     ram
1    ravi
2      ak
3      vj
4      av
5      rj
Name: Name, dtype: str

In [5]:
#select multiple  
df[['Name','Age']]

   Name  Age
0   ram   26
1  ravi   37
2    ak   28
3    vj   19
4    av    4
5    rj    3

In [6]:
df.loc[df.Name=='ravi']

   Name  Age  Monthly_Salary1
1  ravi   37             3000

In [7]:
# select single row || Loc - labell based indexing  || loc rows ko filter/select karta hai 
df.loc[(df.Name=='ram') & (df.Monthly_Salary1>=9000)]

  Name  Age  Monthly_Salary1
0  ram   26            10000

In [8]:
df.loc[0:2]

   Name  Age  Monthly_Salary1
0   ram   26            10000
1  ravi   37             3000
2    ak   28            40000

In [9]:
#select rows || iloc - index-value based 
#df.iloc[0]
df.iloc[0:2]  #[start : stop : step]

   Name  Age  Monthly_Salary1
0   ram   26            10000
1  ravi   37             3000

In [10]:
df.Name=='ravi'

0    False
1     True
2    False
3    False
4    False
5    False
Name: Name, dtype: bool

In [11]:
df.loc[0:2]  # 0 2 include index
df.iloc[0:2]  # [start : stop : step]

   Name  Age  Monthly_Salary1
0   ram   26            10000
1  ravi   37             3000

In [12]:
#5 filter Dataframe - Filtering by column values

In [13]:
df

   Name  Age  Monthly_Salary1
0   ram   26            10000
1  ravi   37             3000
2    ak   28            40000
3    vj   19            50000
4    av    4              555
5    rj    3              777

In [14]:
df['Age']>18

0     True
1     True
2     True
3     True
4    False
5    False
Name: Age, dtype: bool

In [15]:
df[df['Age']>=18]

   Name  Age  Monthly_Salary1
0   ram   26            10000
1  ravi   37             3000
2    ak   28            40000
3    vj   19            50000

In [16]:
df_age_filter = df[df['Age']>=18]  # filter and store dataframe in a new variable

In [17]:
df_age_filter

   Name  Age  Monthly_Salary1
0   ram   26            10000
1  ravi   37             3000
2    ak   28            40000
3    vj   19            50000

In [18]:
df[(df['Age']>=28 )& (df['Monthly_Salary1']>=3000)] #multiple filter condition

   Name  Age  Monthly_Salary1
1  ravi   37             3000
2    ak   28            40000

In [19]:
df.where(df['Age']>=28)  # where fxn replace values in a df based on a condition 
#df[df['Age']>=28]
#Method 
#where()  condition false hone par Nan daalta hai 
#Loc[] false rows ko hata deta hai 
#where() data cleaning and masking mai use hota hai

   Name   Age  Monthly_Salary1
0   NaN   NaN              NaN
1  ravi  37.0           3000.0
2    ak  28.0          40000.0
3   NaN   NaN              NaN
4   NaN   NaN              NaN
5   NaN   NaN              NaN

In [20]:
df.where(df['Age']>=28 , other='Not Eligible')

           Name           Age Monthly_Salary1
0  Not Eligible  Not Eligible    Not Eligible
1          ravi            37            3000
2            ak            28           40000
3  Not Eligible  Not Eligible    Not Eligible
4  Not Eligible  Not Eligible    Not Eligible
5  Not Eligible  Not Eligible    Not Eligible

In [21]:
# 6 Rows & columns - Operations (Add, Update , delete)

In [22]:
df

   Name  Age  Monthly_Salary1
0   ram   26            10000
1  ravi   37             3000
2    ak   28            40000
3    vj   19            50000
4    av    4              555
5    rj    3              777

In [23]:
#create a new column
df['college'] = ['ranjit','itm','mpct','abc','vck','mits']
df

   Name  Age  Monthly_Salary1 college
0   ram   26            10000  ranjit
1  ravi   37             3000     itm
2    ak   28            40000    mpct
3    vj   19            50000     abc
4    av    4              555     vck
5    rj    3              777    mits

In [26]:
#Add new columns using existing coulmns 
df['Bonus'] = df['Monthly_Salary1']*0.20
df

   Name  Age  Monthly_Salary1 college    Bonus
0   ram   26            10000  ranjit   2000.0
1  ravi   37             3000     itm    600.0
2    ak   28            40000    mpct   8000.0
3    vj   19            50000     abc  10000.0
4    av    4              555     vck    111.0
5    rj    3              777    mits    155.4

In [27]:
#Add new row - at the end of dataframe 
df.loc[len(df)] = ['viki',23,2000,'mpct',1000]
df

   Name  Age  Monthly_Salary1 college    Bonus
0   ram   26            10000  ranjit   2000.0
1  ravi   37             3000     itm    600.0
2    ak   28            40000    mpct   8000.0
3    vj   19            50000     abc  10000.0
4    av    4              555     vck    111.0
5    rj    3              777    mits    155.4
6  viki   23             2000    mpct   1000.0

In [28]:
#update value in dataframe using index-value 
df.loc[0,'Monthly_Salary1'] = 5000
df

   Name  Age  Monthly_Salary1 college    Bonus
0   ram   26             5000  ranjit   2000.0
1  ravi   37             3000     itm    600.0
2    ak   28            40000    mpct   8000.0
3    vj   19            50000     abc  10000.0
4    av    4              555     vck    111.0
5    rj    3              777    mits    155.4
6  viki   23             2000    mpct   1000.0

In [29]:
df.loc[df.Name == 'ram','Montly_Salary1'] = 11000
df

   Name  Age  Monthly_Salary1 college    Bonus  Montly_Salary1
0   ram   26             5000  ranjit   2000.0         11000.0
1  ravi   37             3000     itm    600.0             NaN
2    ak   28            40000    mpct   8000.0             NaN
3    vj   19            50000     abc  10000.0             NaN
4    av    4              555     vck    111.0             NaN
5    rj    3              777    mits    155.4             NaN
6  viki   23             2000    mpct   1000.0             NaN

In [30]:
#delete value - rows and columns
df = df.drop(df[df.Name=='viki'].index)  #delete row , axis =0

In [31]:
df

   Name  Age  Monthly_Salary1 college    Bonus  Montly_Salary1
0   ram   26             5000  ranjit   2000.0         11000.0
1  ravi   37             3000     itm    600.0             NaN
2    ak   28            40000    mpct   8000.0             NaN
3    vj   19            50000     abc  10000.0             NaN
4    av    4              555     vck    111.0             NaN
5    rj    3              777    mits    155.4             NaN

In [32]:
#delete row using index-name filter 
df.drop(1,axis=0)

  Name  Age  Monthly_Salary1 college    Bonus  Montly_Salary1
0  ram   26             5000  ranjit   2000.0         11000.0
2   ak   28            40000    mpct   8000.0             NaN
3   vj   19            50000     abc  10000.0             NaN
4   av    4              555     vck    111.0             NaN
5   rj    3              777    mits    155.4             NaN

In [33]:
df.drop('Bonus',axis=1 ,inplace=True) # delete one column

In [34]:
df

   Name  Age  Monthly_Salary1 college  Montly_Salary1
0   ram   26             5000  ranjit         11000.0
1  ravi   37             3000     itm             NaN
2    ak   28            40000    mpct             NaN
3    vj   19            50000     abc             NaN
4    av    4              555     vck             NaN
5    rj    3              777    mits             NaN

In [35]:
df['Bonus'] = df['Monthly_Salary1']*0.20

In [36]:
df.drop(['Bonus'],axis =1, inplace =True)  #delete multiple columns

In [37]:
df

   Name  Age  Monthly_Salary1 college  Montly_Salary1
0   ram   26             5000  ranjit         11000.0
1  ravi   37             3000     itm             NaN
2    ak   28            40000    mpct             NaN
3    vj   19            50000     abc             NaN
4    av    4              555     vck             NaN
5    rj    3              777    mits             NaN

In [38]:
df.rename(columns={'Monthly_Salary1':'Salary'},inplace =True) #rename column name

In [39]:
df

   Name  Age  Salary college  Montly_Salary1
0   ram   26    5000  ranjit         11000.0
1  ravi   37    3000     itm             NaN
2    ak   28   40000    mpct             NaN
3    vj   19   50000     abc             NaN
4    av    4     555     vck             NaN
5    rj    3     777    mits             NaN

In [40]:
#sort values - order values in dataframe by asc or desc order
df.sort_values('Salary')  #ascending oder , by default

   Name  Age  Salary college  Montly_Salary1
4    av    4     555     vck             NaN
5    rj    3     777    mits             NaN
1  ravi   37    3000     itm             NaN
0   ram   26    5000  ranjit         11000.0
2    ak   28   40000    mpct             NaN
3    vj   19   50000     abc             NaN

In [41]:
#sort values - order values in dataframe by asc or desc order
df.sort_values('Salary', ascending =False)  #desecnding oder

   Name  Age  Salary college  Montly_Salary1
3    vj   19   50000     abc             NaN
2    ak   28   40000    mpct             NaN
0   ram   26    5000  ranjit         11000.0
1  ravi   37    3000     itm             NaN
5    rj    3     777    mits             NaN
4    av    4     555     vck             NaN

In [42]:
# create a data column - date of joining 
df['DOJ2'] = ['2024-01-01','2024-01-15','2024-03-28','2024-03-03','2024-04-03','2024-05-01']
df

   Name  Age  Salary college  Montly_Salary1        DOJ2
0   ram   26    5000  ranjit         11000.0  2024-01-01
1  ravi   37    3000     itm             NaN  2024-01-15
2    ak   28   40000    mpct             NaN  2024-03-28
3    vj   19   50000     abc             NaN  2024-03-03
4    av    4     555     vck             NaN  2024-04-03
5    rj    3     777    mits             NaN  2024-05-01

In [43]:
df['DOJ2'].dtype  #object -type value 
#dtype('O')

In [77]:
df['DOJ2'] = pd.to_datetime(df['DOJ2']) # change to data -time type

In [80]:
df['DOJ2'].dtype  #date-time type

dtype('<M8[us]')

In [81]:
df1 =df

In [82]:
#creating a new column with incorect date format
df1['DOJ3'] = ['01-01-2025','15-01-2025','28-03-2025','03-03-2025','03-03-2025','03-03-2025']

In [89]:
#extract year , month, day
df['DOJ2'].dt.year
# df['DOJ2'].dt.month
# df['DOJ2'].dt.day
# df['DOJ2'].dt.day_name()

0    2024
1    2024
2    2024
3    2024
4    2024
5    2024
Name: DOJ2, dtype: int32

In [91]:
#create a new column using month extract function from DOJ2 column
df['Month'] = df['DOJ2'].dt.month

In [92]:
df

   Name  Age  Salary college  Montly_Salary1       DOJ2        DOJ3  Month
0   ram   26    5000  ranjit         11000.0 2024-01-01  01-01-2025      1
1  ravi   37    3000     itm             NaN 2024-01-15  15-01-2025      1
2    ak   28   40000    mpct             NaN 2024-03-28  28-03-2025      3
3    vj   19   50000     abc             NaN 2024-03-03  03-03-2025      3
4    av    4     555     vck             NaN 2024-04-03  03-03-2025      4
5    rj    3     777    mits             NaN 2024-05-01  03-03-2025      5

In [93]:
df['DOJ2'] + pd.Timedelta(days=90) # add 90 days to DOJ2 column

0   2024-03-31
1   2024-04-14
2   2024-06-26
3   2024-06-01
4   2024-07-02
5   2024-07-30
Name: DOJ2, dtype: datetime64[us]